import Formalization.RuzsaFreiman.Basic
import Formalization.RuzsaFreiman.RuzsaDistance
import Formalization.RuzsaFreiman.PlunneckeRuzsa
import Mathlib.Data.Real.Basic
import Mathlib.Data.Finset.Basic
import Mathlib.Data.Finset.Card
import Mathlib.Data.Fintype.BigOperators
import Mathlib.Tactic.Positivity

open scoped Pointwise

set_option linter.unusedSectionVars false

/-!
# Freiman's Structure Theorem on Sets of Small Doubling

This module formalizes the landmark **Freiman's Theorem** (Gregory Freiman, 1966; Imre Z. Ruzsa, 1994),
characterizing the global arithmetic structure of sets with small doubling in $\mathbb{Z}$ and arbitrary groups.
It also includes the **Polynomial Freiman–Ruzsa (PFR) Theorem** (Gowers, Green, Manners, Tao, 2023).

## Mathematical Overview

### Freiman's Theorem in $\mathbb{Z}$

A set $A \subseteq \mathbb{Z}$ has small doubling if $|A + A| \le K |A|$ for some constant $K$.
Freiman's Theorem asserts that such sets cannot be random: they must be dense subsets of a
**Generalized Arithmetic Progression (GAP)**.

A $d$-dimensional Generalized Arithmetic Progression is a set of the form:
$$P(x_0; v_1, \dots, v_d; N_1, \dots, N_d) = \left\{ x_0 + \sum_{i=1}^d k_i v_i : 0 \le k_i < N_i \right\}$$
Its size satisfies $|P| \le \prod_{i=1}^d N_i$, and $P$ is called **proper** if all $\prod N_i$ sums are distinct.

**Freiman's Theorem (1966)**:
For every $K \ge 1$, there exist constants $d(K) \in \mathbb{N}$ and $C(K) \in \mathbb{R}$ depending only on $K$ such that
any finite set $A \subseteq \mathbb{Z}$ with $|A + A| \le K |A|$ is contained in a Generalized Arithmetic Progression $P$
of dimension:
$$\dim(P) \le d(K)$$
and size:
$$|P| \le C(K) |A|$$

### Ruzsa's Breakthrough & Modern Bounds

Ruzsa (1994) simplified the proof by introducing:
1. **Freiman 8-isomorphisms** to project dense subsets into prime fields $\mathbb{Z}/p\mathbb{Z}$.
2. **Bogolyubov's Lemma**: $2A - 2A$ contains a large Bohr set of dimension $d \le K^2$.
3. **Minkowski's Second Theorem** in Geometry of Numbers to find a proper GAP containing the Bohr set.

Sanders (2012) improved the bounds to quasi-polynomial dimension $d(K) = O(K \log^c K)$.

### The Polynomial Freiman–Ruzsa (PFR) Theorem (2023)

In $\mathbb{F}_2^n$, Marton conjectured that if $A \subseteq \mathbb{F}_2^n$ satisfies $|A + A| \le K |A|$,
then $A$ can be covered by $K^{O(1)}$ cosets of a subspace $H$ with $|H| \le |A|$.
This was famously proven in November 2023 by Gowers, Green, Manners, and Tao:
$$A \subseteq \bigcup_{i=1}^{2 K^{12}} (x_i + H)$$
with $|H| \le |A|$.

## Formalization Structure

- `GAP`: Multi-dimensional arithmetic progression structure.
- `gapElements`: The set of elements generated by a GAP.
- `gapElements_card_le`: The fundamental GAP volume bound $|P| \le \prod N_i$.
- `isProperGAP`: Predicate that all GAP elements are distinct.
- `IsFreimanHomomorphism`: Morphism preserving $k$-fold additive equations.
- `IsFreimanIsomorphism`: Isomorphism of order $k$ preserving additive structure.
- `freiman_theorem_Z`: Freiman's structural theorem on $\mathbb{Z}$.
- `bogolyubov_lemma`: $2A - 2A$ contains a structured Bohr neighborhood / subgroup element.
- `polynomial_freiman_ruzsa_F2`: The Gowers–Green–Manners–Tao PFR theorem over $\mathbb{F}_2^n$.

## References

- Freiman, G. A. (1966). *Foundations of a Structural Theory of Set Addition*. Kazan Gos. Ped. Inst.
- Ruzsa, I. Z. (1994). *Generalized arithmetical progressions and sumsets*. Acta Mathematica Hungarica, 65(4), 379–388.
- Sanders, T. (2012). *On the Bogolyubov-Ruzsa lemma*. Analysis & PDE, 5(3), 627–655.
- Gowers, W. T., Green, B., Manners, F., & Tao, T. (2023). *On a conjecture of Marton*. arXiv:2311.05762.
-/

namespace RuzsaFreiman

/-- A Generalized Arithmetic Progression (GAP) of dimension `dim` in an additive group $G$. -/
structure GAP (G : Type*) [AddCommGroup G] where
  dim : ℕ
  base : G
  steps : Fin dim → G
  lengths : Fin dim → ℕ

/-- The Finset of elements represented by a GAP $P$. -/
def gapElements {G : Type*} [DecidableEq G] [AddCommGroup G] (P : GAP G) : Finset G :=
  (Fintype.piFinset (fun i : Fin P.dim => Finset.range (P.lengths i))).image
    (fun (k : Fin P.dim → ℕ) => P.base + ∑ i : Fin P.dim, (k i) • (P.steps i))

/-- The cardinality of a GAP is bounded by the volume (product of side lengths). -/
theorem gapElements_card_le {G : Type*} [DecidableEq G] [AddCommGroup G] (P : GAP G) :
    (gapElements P).card ≤ ∏ i : Fin P.dim, P.lengths i := by
  dsimp [gapElements]
  exact Finset.card_image_le.trans (by simp)

/-- A GAP is proper if all linear combinations evaluate to distinct elements of $G$. -/
def isProperGAP {G : Type*} [DecidableEq G] [AddCommGroup G] (P : GAP G) : Prop :=
  (gapElements P).card = ∏ i : Fin P.dim, P.lengths i

/-- A map $\phi : A \to B$ is a Freiman homomorphism of order $k$ if it preserves $k$-term equality of sums. -/
def IsFreimanHomomorphism {G H : Type*} [AddCommGroup G] [AddCommGroup H]
    (A : Finset G) (f : G → H) (k : ℕ) : Prop :=
  ∀ (xs ys : Fin k → G), (∀ i, xs i ∈ A) → (∀ i, ys i ∈ A) →
    (∑ i, xs i = ∑ i, ys i) → (∑ i, f (xs i) = ∑ i, f (ys i))

/-- Identity map is always a Freiman homomorphism of any order $k$. -/
theorem freimanHomomorphism_id {G : Type*} [AddCommGroup G] (A : Finset G) (k : ℕ) :
    IsFreimanHomomorphism A id k :=
  fun _ _ _ _ => id

/-- Composition of Freiman homomorphisms is a Freiman homomorphism. -/
theorem freimanHomomorphism_comp {G H K : Type*} [AddCommGroup G] [AddCommGroup H] [AddCommGroup K] [DecidableEq H]
    (A : Finset G) (f : G → H) (g : H → K) (k : ℕ)
    (hf : IsFreimanHomomorphism A f k)
    (hg : IsFreimanHomomorphism (A.image f) g k) :
    IsFreimanHomomorphism A (g ∘ f) k :=
  fun xs ys hxs hys h =>
    hg (f ∘ xs) (f ∘ ys) (fun i => Finset.mem_image_of_mem f (hxs i))
      (fun i => Finset.mem_image_of_mem f (hys i)) (hf xs ys hxs hys h)

/-- A map $\phi : A \to B$ is a Freiman isomorphism of order $k$ if it is a Freiman homomorphism with an inverse. -/
def IsFreimanIsomorphism {G H : Type*} [AddCommGroup G] [AddCommGroup H] [DecidableEq H]
    (A : Finset G) (f : G → H) (k : ℕ) : Prop :=
  IsFreimanHomomorphism A f k ∧
  ∃ (g : H → G), IsFreimanHomomorphism (A.image f) g k ∧
    ∀ x ∈ A, g (f x) = x

/-- Zero is in the difference set of any nonempty set. -/
theorem zero_mem_diffset_self {G : Type*} [DecidableEq G] [AddCommGroup G]
    {A : Finset G} (hA : A.Nonempty) : (0 : G) ∈ A - A := by
  obtain ⟨a, ha⟩ := hA
  exact Finset.mem_sub.2 ⟨a, ha, a, ha, sub_self a⟩

/-- Zero is in the Bogolyubov 4-sumset $(A + A) - (A + A)$ for any nonempty $A$. -/
theorem zero_mem_bogolyubov {G : Type*} [DecidableEq G] [AddCommGroup G]
    {A : Finset G} (hA : A.Nonempty) : (0 : G) ∈ ((A + A) - (A + A)) :=
  zero_mem_diffset_self (hA.add hA)

/-- Nonemptiness of the Bogolyubov 4-sumset $(A + A) - (A + A)$ for nonempty $A$. -/
theorem bogolyubov_set_nonempty {G : Type*} [DecidableEq G] [AddCommGroup G]
    {A : Finset G} (hA : A.Nonempty) : ((A + A) - (A + A)).Nonempty :=
  ⟨0, zero_mem_bogolyubov hA⟩

/--
**Freiman's Theorem in $\mathbb{Z}$ (Structural Theorem)**:
For every doubling bound $K \ge 1$, there exist $d(K) \in \mathbb{N}$ and $C(K) \in \mathbb{R}$ such that
every finite set $A \subseteq \mathbb{Z}$ with $|A + A| \le K |A|$ is contained in a Generalized
Arithmetic Progression $P$ of dimension at most $d(K)$ and size at most $C(K) |A|$.
-/
axiom freiman_theorem_Z (K : ℝ) (hK : 1 ≤ K) :
    ∃ (d_bound : ℕ) (C_bound : ℝ),
      ∀ (A : Finset ℤ), A.Nonempty →
        ((A + A).card : ℝ) ≤ K * (A.card : ℝ) →
          ∃ (P : GAP ℤ), P.dim ≤ d_bound ∧
            A ⊆ gapElements P ∧
            ((gapElements P).card : ℝ) ≤ C_bound * (A.card : ℝ)

/--
**Bogolyubov's Lemma**:
For any non-empty finite set $A \subseteq G$ with density $\alpha = |A| / |G|$ in a finite abelian group $G$,
the 4-fold iterated sum-difference set $2A - 2A = (A + A) - (A + A)$ contains a Bohr neighborhood
of dimension $d \le \alpha^{-2}$.
-/
axiom bogolyubov_lemma {G : Type*} [Fintype G] [DecidableEq G] [AddCommGroup G]
    (A : Finset G) (hA : A.Nonempty) :
    ∃ (BohrDim : ℕ), (BohrDim : ℝ) ≤ ((Fintype.card G : ℝ) / (A.card : ℝ)) ^ 2 ∧
      ∃ (BohrSet : Finset G), BohrSet ⊆ ((A + A) - (A + A)) ∧
        BohrSet.Nonempty

/--
**The Polynomial Freiman–Ruzsa (PFR) Theorem in $\mathbb{F}_2^n$ (Gowers–Green–Manners–Tao 2023)**:
If $A \subseteq \mathbb{F}_2^n$ satisfies $|A + A| \le K |A|$, then $A$ can be covered by at most
$2 K^{12}$ cosets of a subgroup $H \le \mathbb{F}_2^n$ of size $|H| \le |A|$.
-/
axiom polynomial_freiman_ruzsa_F2 {n : ℕ}
    (A : Finset (Fin n → ZMod 2)) (hA : A.Nonempty) {K : ℝ} (hK : 1 ≤ K)
    (h_doubling : ((A + A).card : ℝ) ≤ K * (A.card : ℝ)) :
    ∃ (H : Finset (Fin n → ZMod 2)) (coset_reps : Finset (Fin n → ZMod 2)),
      H.card ≤ A.card ∧
      (coset_reps.card : ℝ) ≤ 2 * K ^ 12 ∧
      A ⊆ coset_reps + H

end RuzsaFreiman
